### ISSUE TITLE
PHP VERSION

### ISSUE THREAD

**Issue by khalid-sanggoyod** [adsr/phpspy#140]
Is PHP 8.3 not supported on phpspy? 

![image](https://github.com/adsr/phpspy/assets/48314544/3a2bf533-6727-4da2-b057-1f2d784b3dd8)

**Comment by khalid-sanggoyod** [comment]
What does this mean "No such process"?

![image](https://github.com/adsr/phpspy/assets/48314544/65f362e1-7f17-4f1c-b898-81b1790a5c2c)

I have a sample PHP script which is a test.php file and I want to test if this PHPspy tool can analyze or trace the slow function.

**Comment by adsr** [comment]
Hello, yes 8.3 is supported. The first error looks like the script is finishing before phpspy has a chance to attach. In the second example, I think you should drop the `-r` flag otherwise the path itself will be executed as erroneous PHP code.

You can test if PHP is working by doing something like this:

```
$ phpspy -- php -r 'sleep(1);'
```

If your script is running too quickly you can try wrapping it in a loop.
