### ISSUE TITLE
can't compile on OSX, missing libpthread

### ISSUE THREAD

**Issue by dseguy** [adsr/phpspy#49]
With a freshly updated repo, I try to `make`  phpspy : 
```
phpspy$ make
Makefile:22: *** Need libpthread.  Stop.

```
libpthread is installed, available in /usr/lib/libpthread.dylib 
$LDFLAGS is empty

a direct call to ld gives this (based on the Makefile that leads to the failure)  : 
```
$ ld -lpthread 
ld: warning: No version-min specified on command line
ld: warning: -arch not specified
ld: warning: -macosx_version_min not specified, assuming 10.11
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for inferred architecture x86_64
```

How can I fix this ?

**Comment by adsr** [comment]
Hi, unfortunately phpspy is Linux only right now. I filed issues for macOS (#50) and Windows support (#51).

**Comment by paslandau** [comment]
Hey @adsr ,
 
I got the same error `Makefile:22: *** Need libpthread.  Stop.` using a docker container based on https://github.com/phusion/baseimage-docker

After "blindly" installing everything mentioned in https://github.com/adsr/phpspy/issues/45 it works (at least I can run `make` without errors). Would still be good to understand what exactly I was missing since googling for `libpthread` doesn't provide much help.

Cheers
Pascal

**Comment by adsr** [comment]
Hi @paslandau, libpthread (POSIX threads) should be provided by the libc package. I am not sure why it can't be found on your setup. I tried reproducing with the steps below but could not.

```
docker run --rm -t -i phusion/baseimage /sbin/my_init -- bash -l
apt update
apt install -y git # for git clone
apt install -y build-essential # for gcc and make
apt install -y python # for compiling termbox with waf (python)
git clone --recursive https://github.com/adsr/phpspy.git
cd phpspy
make
```

**Comment by DanielRuf** [comment]
> After "blindly" installing everything mentioned in #45 it works (at least I can run `make` without errors)

For me this did not work as some of them are also not available in homebrew/core.
